export const skillData = [
    {
      id: 1,
      number: '11',
      korTitle: '카운트효과',
      engTitle: 'Count',
      description: '정수값을 변수에 넣어 3자리마다 쉼표로 구분하였습니다.',
      type: 'jquery',
      type2: 'javascript',
    },
    {
        id: 2,
        number: '02',
        korTitle: '아코디언 슬라이더',
        engTitle: 'Acodian Slider',
        description: '아코디언 형태의 슬라이더입니다.',
        type: 'html5',
        type2: 'css',
    },
    {
        id: 3,
        number: '07',
        korTitle: '파도효과',
        engTitle: 'Wave',
        description: 'CANVAS로 파도효과 구현',
        type: 'canvas',
        type2: 'css',
    },
    {
        id: 4,
        number: '10',
        korTitle: '스크롤매직',
        engTitle: 'Scroll-Magic',
        description: '스크롤트리거, gsap을 활용하여 만든 스크롤 예제입니다.',
        type: 'jquery',
        type2: 'plugin',
    },
    {
        id: 5,
        number: '11',
        korTitle: '타이핑효과',
        engTitle: 'Typing',
        description: '타이핑하듯이 글자가 출력되는 예제입니다.',
        type: 'jquery',
        type2: 'javascript',
    },
    {
        id: 6,
        number: '08',
        korTitle: '카드게임',
        engTitle: 'Card Game',
        description: '카드 뒤집기 게임입니다.',
        type: 'jquery',
        type2: 'javascript',
    },
    {
        id: 7,
        number: '09',
        korTitle: '랜덤썸네일',
        engTitle: 'Random-Thumbnail',
        description: '빈 이미지에 랜덤값으로 이미지가 부여되도록 설정한 예제입니다.',
        type: 'jquery',
        type2: 'javascript',
    },
    {
        id: 8,
        number: '12',
        korTitle: 'vue.js 스터디예제',
        engTitle: 'vue.js Study Ex)',
        description: 'vue.js 독학하며 실습헀던 내용입니다.',
        type: 'vue',
        type2: 'javascript',
    },
    {
        id: 9,
        number: '13',
        korTitle: '그물효과',
        engTitle: 'Net Effect',
        description: '구글링 중 신기한 canvas 효과가 있어서 로컬에 적용해보았습니다.',
        type: 'canvas',
        type2: 'css',
    },
]