export const timelineData = [
    {
      id: 1,
      class: 'jnet',
      company: '제이넷',
      department: 'UI/UX팀',
      rank: '대리',
      date: '2021.03 ~ 2024.04',
      text: '도서관 및 공공기관 프로젝트 구축, 리뉴얼, 솔루션 업데이트, 유지보수',
      description: '성남시청, 국립중앙도서관, 성남시립도서관, 화성시립도서관, 동대문구립도서관, 중구구립도서관, 서대문구립도서관, 하상장애인복지관, 남양주시도서관...',
    },
    {
      id: 2,
      class: 'wisa',
      company: '위사',
      department: 'UX그룹',
      rank: '대리',
      date: '2020.07 ~ 2020.12',
      text: '자체 서비스 발굴 및 개발 / 대기업 온라인쇼핑몰 프로젝트 구축 대행',
      description: 'IDF MALL, 대현인사이드, 지오다노, 에스더포뮬러, 이현어패럴, 남유네, ANANTI, 용대황태푸드, 인동에프엔...',
    },
    {
      id: 3,
      class: 'design',
      company: '디자인주식회사',
      department: 'IT팀',
      rank: '대리',
      date: '2020.01 ~ 2020.06',
      text: '자사 쇼핑몰 관리 및 기업페이지 리뉴얼, 유지보수',
      description: '디자인주식회사 홈페이지, 코끼리 STORE, 코끼리 SMART STORE, 코끼리 B2B, 코끼리 BOX, Dr.Bella...',
    },
    {
      id: 4,
      class: 'eims',
      company: '아임스인터내셔널',
      department: '시스템관리부',
      rank: '사원',
      date: '2018.11 ~ 2020.01',
      text: '사전등록페이지 및 홈페이지 제작, 웹디자인, 웹메일',
      description: 'SPOEX, In-cosmetics Korea, Semicon-korea, 베이비페어, NU-SKIN, K-fairs...',
    },
    {
      id: 5,
      class: 'sisoft',
      company: '에스아이소프트',
      department: '디자인팀',
      rank: '사원',
      date: '2018.07 ~ 2018.11',
      text: '블로그 위젯코드 제작, 스킨 제작, 자사솔루션 기능개선',
      description: '네이버 블로그 스킨, 자사솔루션 웹페이지 제작, 부동산 관련 홈페이지 제작',
    },
    {
      id: 6,
      class: 'nsglobal',
      company: '엔에스글로벌',
      department: '시스템관리부',
      rank: '사원',
      date: '2017.01 ~ 2017.08',
      text: '자사 오픈마켓 관리, HTML, 문서작성, 더존, 전산입력',
      description: 'G마켓, 11번가, 옥션 오픈마켓 관리, 내부 HTML 관리',
    },
]