export const workData = [
    {
      id: 1,
      type: 'shop',
      number: '01',
      korTitle: 'IDF 몰',
      engTitle: 'IDF MALL',
      date: '2020.07 ~ 2020.09',
      client: '인동에프엔',
      mainColor: '#000',
      subColor: '#fff',
    },
    {
      id: 2,
      type: 'shop',
      number: '02',
      korTitle: '대현인사이드',
      engTitle: 'Daehyun Inside',
      date: '2020.08 ~ 2020.11',
      client: '(주)대현',
      mainColor: '#000',
      subColor: '#fff',
    },
    {
      id: 3,
      type: 'shop',
      number: '06',
      korTitle: '지오다노',
      engTitle: 'GIORDANO',
      date: '2020.10 ~ 2020.11',
      client: '(주)지오다노',
      mainColor: '#000',
      subColor: '#fff',
    },
    {
      id: 4,
      type: 'shop',
      number: '05',
      korTitle: '이현어패럴',
      engTitle: 'IH MALL',
      date: '2020.09 ~ 2020.10',
      client: '(주)이현어패럴',
      mainColor: '#000',
      subColor: '#fff',
    },
    {
      id: 5,
      type: 'shop',
      number: '04',
      korTitle: '에스더몰',
      engTitle: 'ESTHER MALL',
      date: '2020.10 ~ 2020.12',
      client: '에스더포뮬러(주)',
      mainColor: '#000',
      subColor: '#fff',
    },
    {
      id: 6,
      type: 'shop',
      number: '03',
      korTitle: '셀렉온',
      engTitle: 'CELECON',
      date: '2020.09 ~ 2020.10',
      client: '(주)셀렉온',
      mainColor: '#000',
      subColor: '#fff',
    },
    {
      id: 7,
      type: 'lib',
      number: '22',
      korTitle: '성남시 생활민원사이트',
      engTitle: 'One-Stop',
      date: '2022.11 ~ 2022.12',
      client: '성남시청',
      mainColor: '#bfd2e1',
      subColor: '#ecc8d4',
    },
    {
      id: 8,
      type: 'lib',
      number: '24',
      korTitle: '성남시청',
      engTitle: 'SeongNam CityHall',
      date: '2023.04 ~ 2023.08',
      client: '성남시청',
      mainColor: '#d84048',
      subColor: '#f8dee0',
    },
    {
      id: 9,
      type: 'lib',
      number: '14',
      korTitle: '성남육아종합지원센터',
      engTitle: 'Sneducare',
      date: '2021.09 ~ 2021.12',
      client: '성남시육아종합지원센터',
      mainColor: '#2653b0',
      subColor: '#7595cb',
    },
    {
      id: 10,
      type: 'lib',
      number: '11',
      korTitle: '서대문구립도서관',
      engTitle: 'SeoDaeMun Lib',
      date: '2022.11 ~ 2022.12',
      client: '서대문구립도서관',
      mainColor: '#6b6ab0',
      subColor: '#8f8ed4',
    },
    {
      id: 11,
      type: 'lib',
      number: '01',
      korTitle: '강남구립도서관',
      engTitle: 'Gangnam-gu Lib',
      date: '2021.06 ~ 2021.09',
      client: '강남구도서관사업소',
      mainColor: '#3598db',
      subColor: '#0a518f',
    },
    {
      id: 12,
      type: 'lib',
      number: '21',
      korTitle: '강동구북카페',
      engTitle: 'Gangdong BookCafe',
      date: '2021.12 ~ 2022.02',
      client: '강동구북카페',
      mainColor: '#5d3a1e',
      subColor: '#824714',
    },
    {
      id: 13,
      type: 'lib',
      number: '12',
      korTitle: '서울아트책보고',
      engTitle: 'Art BookBoGo',
      date: '2022.09 ~ 2023.03',
      client: '(주)더그림',
      mainColor: '#f45104',
      subColor: '#ffd900',
    },
    {
      id: 14,
      type: 'lib',
      number: '04',
      korTitle: '고양시립도서관',
      engTitle: 'Goyang Library',
      date: '2022.11 ~ 2023.06',
      client: '고양시도서관사업소',
      mainColor: '#967759',
      subColor: '#bca280',
    },
    {
      id: 15,
      type: 'lib',
      number: '15',
      korTitle: '송파구립도서관',
      engTitle: 'Songpa Library',
      date: '2021.08 ~ 2022.02',
      client: '송파구도서관사업소',
      mainColor: '#3a5fc9',
      subColor: '#8ba9fc',
    }
];

export const result = workData.reduce((acc, curr) => {
  const { type } = curr;
  if (acc[type]) acc[type].push(curr);  // [3]
  else acc[type] = [curr];              // [4]
  return acc;  

}, {});
